Repository Team-SE-MO/semo-react-server, pull requests merged in 2024-10, with the labels that each got.

#2 [Feat] 공통 컴포넌트(button, input) 구현
  src/components/atoms/button/Button.scss
  src/components/atoms/button/Button.tsx
  src/components/atoms/input/Input.scss
  src/components/atoms/input/Input.tsx
  src/styles/_variables.scss
Labels: 🎨 Design, ✨ Feat

#5 [Feat] : 공통 컴포넌트 text 구현
  src/components/atoms/text/Text.scss
  src/components/atoms/text/Text.tsx
Labels: 🎨 Design, ✨ Feat

#7 [Chore] router 설정
  package-lock.json
  package.json
  src/App.tsx
  src/pages/CompanyRequests.tsx
  src/pages/CompanyUsers.tsx
  src/pages/Dashboard.tsx
  src/pages/Devices.tsx
  src/pages/ForgetPassword.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  src/pages/MainLayout.tsx
  src/pages/SignUp.tsx
  src/pages/Summary.tsx
  src/pages/UserRequests.tsx
  src/pages/Users.tsx
  src/pages/index.tsx
Labels: 🍎 Chore

#9 [Feat] Main페이지 구현
  src/components/atoms/text/Text.scss
  src/components/atoms/text/Text.tsx
  src/components/organisms/welcome/Welcome.scss
  src/components/organisms/welcome/Welcome.tsx
  src/pages/Main.scss
  src/pages/Main.tsx
  src/pages/MainLayout.tsx
Labels: 🎨 Design, ✨ Feat

#11 [Feat] button, input 수정 및 유저 프로필 구현
  package-lock.json
  package.json
  src/components/atoms/button/Button.scss
  src/components/atoms/button/Button.tsx
  src/components/atoms/dropdown/DropdownItem.scss
  src/components/atoms/dropdown/DropdownItem.tsx
  src/components/atoms/index.tsx
  src/components/atoms/input/Input.scss
  src/components/atoms/input/Input.tsx
  src/components/atoms/profile/ProfileIcon.scss
  src/components/atoms/profile/ProfileIcon.tsx
  src/components/molecules/dropdown/Dropdown.scss
  src/components/molecules/dropdown/Dropdown.tsx
  src/components/molecules/index.tsx
  src/components/molecules/profile/Profile.scss
  src/components/molecules/profile/Profile.tsx
  src/types/Company.ts
  src/types/Device.ts
Labels: 🎨 Design, ✨ Feat, ♻️ Refactor

#13 [Feat] 로그인 페이지 구현
  package-lock.json
  package.json
  src/pages/Login.scss
  src/pages/Login.tsx
  src/services/index.ts
  src/services/index.tsx
Labels: 🎨 Design, ✨ Feat

#15 [Feat] 비밀번호 변경 페이지 구현
  src/App.tsx
  src/pages/ChangePassword.scss
  src/pages/ChangePassword.tsx
  src/pages/ForgetPassword.tsx
  src/pages/Login.tsx
Labels: 🎨 Design, ✨ Feat

#16 [Feat] 회원 가입 페이지 및 메인레이아웃 구현
  src/assets/images/semo_logo_footer.svg
  src/assets/images/semo_logo_header.svg
  src/components/atoms/dropdown/DropdownItem.scss
  src/components/atoms/text/Text.scss
  src/components/atoms/text/Text.tsx
  src/components/molecules/dropdown/Dropdown.scss
  src/components/molecules/profile/Profile.scss
  src/components/molecules/profile/Profile.tsx
  src/components/molecules/profiledetail/ProfileDropdown.scss
  src/components/molecules/profiledetail/ProfileDropdown.tsx
  src/components/organisms/footer/Footer.scss
  src/components/organisms/footer/Footer.tsx
  src/components/organisms/header/Header.scss
  src/components/organisms/header/Header.tsx
  src/components/organisms/modal/CompanyRegister.scss
  src/components/organisms/modal/CompanyRegister.tsx
  src/components/organisms/welcome/Welcome.tsx
  src/pages/ChangePassword.tsx
  src/pages/Login.tsx
  src/pages/MainLayout.tsx
  src/pages/SignUp.scss
  src/pages/SignUp.tsx
Labels: 🎨 Design, ✨ Feat

#19 [Feat] 회사 등록 요청 조회 페이지 구현
  src/components/molecules/button/PageButton.tsx
  src/components/molecules/table/CompanyReqRow.tsx
  src/components/organisms/table/Table.tsx
  src/pages/CompanyRequests.scss
  src/pages/CompanyRequests.tsx
Labels: 🎨 Design, ✨ Feat
