Repository Team-SE-MO/semo-react-server, pull requests merged in 2024-11, with the labels that each got.

#26 [Feat] Device 장비 관리 정보 페이지 구현
  src/components/molecules/table/DevicesRow.tsx
  src/pages/Devices.scss
  src/pages/Devices.tsx
Labels: 🎨 Design, ✨ Feat

#25 [Feat] Device 요약 페이지 구현
  src/assets/images/oracle_icon.svg
  src/pages/Devices.tsx
  src/pages/Summary.scss
  src/pages/Summary.tsx
  src/pages/Users.tsx
Labels: 🎨 Design, ✨ Feat

#30 [Feat] 로그인 API 연결
  package-lock.json
  package.json
  src/pages/Login.tsx
  src/services/index.ts
  src/services/user.ts
  src/store/index.tsx
  src/store/useAuthStore.ts
  src/types/Company.ts
  src/types/Device.ts
  src/types/Role.ts
  src/types/index.tsx
Labels: ✨ Feat

#31 [Refactor] 메인메뉴, 회원가입, 레이아웃 리팩토링 진행
  src/components/atoms/button/Button.tsx
  src/components/atoms/dropdown/DropdownItem.scss
  src/components/atoms/text/Text.scss
  src/components/atoms/text/Text.tsx
  src/components/molecules/dropdown/Dropdown.scss
  src/components/molecules/profiledetail/ProfileDropdown.scss
  src/components/molecules/profiledetail/ProfileDropdown.tsx
  src/components/organisms/footer/Footer.scss
  src/components/organisms/footer/Footer.tsx
  src/components/organisms/header/Header.scss
  src/components/organisms/header/Header.tsx
  src/components/organisms/modal/CompanyRegister.scss
  src/components/organisms/modal/CompanyRegister.tsx
  src/components/organisms/welcome/Welcome.scss
  src/components/organisms/welcome/Welcome.tsx
  src/pages/MainLayout.tsx
  src/pages/SignUp.scss
Labels: 🎨 Design, ✨ Feat, ♻️ Refactor

#33 [Feat] 회사, 회원 등록 폼 제출 API 연결
  src/components/organisms/modal/CompanyRegister.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/services/company.ts
  src/services/index.ts
  src/services/user.ts
  src/types/Company.ts
Labels: ✨ Feat

#36 [Feat] 모니터링 페이지 차트 구현
  src/App.tsx
  src/components/molecules/chart/ActiveTotalSessionChart.tsx
  src/components/molecules/chart/BlockingWaitSessionChart.tsx
  src/components/molecules/chart/Chart.tsx
  src/components/molecules/chart/ChartCollection.tsx
  src/components/molecules/chart/SessionCountGroupChart.tsx
  src/components/organisms/device/MetricChart.tsx
  src/components/organisms/header/Header.scss
  src/pages/Dashboard.scss
  src/pages/Dashboard.tsx
  src/services/deviceMonitoring.ts
  src/types/ChartData.ts
  src/utils/.gitkeep
  src/utils/convertSessionCountByKey.ts
Labels: 🎨 Design, ✨ Feat

#38 [Feat] API 연결 - 폼 요청 조회, 비밀번호 변경, 요약 페이지
  src/components/atoms/text/Text.tsx
  src/components/molecules/table/CompanyReqRow.tsx
  src/components/molecules/table/CompanyUserRow.tsx
  src/components/molecules/table/DevicesRow.tsx
  src/components/molecules/table/UserReqRow.tsx
  src/components/molecules/table/UserRow.tsx
  src/components/organisms/device/MetricChart.tsx
  src/components/organisms/table/Table.tsx
  src/pages/ChangePassword.scss
  src/pages/ChangePassword.tsx
  src/pages/CompanyRequests.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/pages/Summary.scss
  src/pages/Summary.tsx
  src/pages/UserRequests.tsx
  src/services/company.ts
  src/services/deviceMonitoring.ts
  src/services/email.ts
  src/services/user.ts
Labels: ✨ Feat, ⭐️ Style

#40 [Feat] 유저 관리 페이지 API 연결
  package-lock.json
  package.json
  src/components/molecules/profiledetail/ProfileDropdown.scss
  src/components/molecules/profiledetail/ProfileDropdown.tsx
  src/components/molecules/table/CompanyUserRow.tsx
  src/components/molecules/table/UserRow.tsx
  src/components/organisms/header/Header.scss
  src/components/organisms/header/Header.tsx
  src/components/organisms/modal/CompanyRegister.tsx
  src/components/organisms/modal/UserRegister.scss
  src/components/organisms/modal/UserRegister.tsx
  src/components/organisms/table/Table.tsx
  src/pages/ChangePassword.tsx
  src/pages/CompanyUsers.scss
  src/pages/CompanyUsers.tsx
  src/pages/Devices.tsx
  src/pages/Login.tsx
  src/pages/Users.tsx
  src/services/user.ts
  src/store/useAuthStore.ts
Labels: 🍎 Chore, ✨ Feat, :hammer: Fix

#45 [Fix] 요약 페이지 수정
  src/pages/ChangePassword.tsx
  src/pages/Dashboard.tsx
  src/pages/Summary.scss
  src/pages/Summary.tsx
Labels: ✨ Feat, :hammer: Fix

#46 [Design] SweetAlert 적용
  src/components/atoms/text/Text.tsx
  src/components/molecules/profiledetail/ProfileDropdown.tsx
  src/components/molecules/table/CompanyReqRow.tsx
  src/components/molecules/table/UserReqRow.tsx
  src/components/organisms/modal/CompanyRegister.tsx
  src/components/organisms/modal/DatabaseForm.tsx
  src/components/organisms/modal/UserRegister.tsx
  src/pages/ChangePassword.tsx
  src/pages/CompanyUsers.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
  src/pages/Users.tsx
Labels: 🎨 Design, :hammer: Fix

#47 [Refactor] 모달, 헤더, css 수정진행
  src/components/molecules/table/UserReqRow.scss
  src/components/molecules/table/UserReqRow.tsx
  src/components/organisms/modal/DatabaseDelete.scss
  src/components/organisms/modal/DatabaseForm.scss
  src/components/organisms/modal/UserRegister.scss
Labels: ♻️ Refactor, ⭐️ Style

#50 [Refactor] Table SCSS 개선
  src/components/molecules/table/CompanyReqRow.tsx
  src/components/molecules/table/CompanyUserRow.tsx
  src/components/molecules/table/DevicesRow.tsx
  src/components/molecules/table/UserReqRow.tsx
  src/components/molecules/table/UserRow.tsx
  src/components/organisms/table/Table.scss
  src/components/organisms/table/Table.tsx
  src/pages/CompanyRequests.scss
  src/pages/Devices.scss
Labels: 🎨 Design, ♻️ Refactor

#52 [Refactor] 로그인, 요청관리 페이지 리팩토링
  src/App.tsx
  src/components/atoms/button/Button.scss
  src/components/molecules/button/PageButton.tsx
  src/components/molecules/button/RequestPageButtons.scss
  src/components/molecules/button/RequestPageButtons.tsx
  src/components/molecules/dropdown/Dropdown.scss
  src/components/molecules/table/CompanyReqRow.tsx
  src/components/molecules/table/UserReqRow.scss
  src/components/molecules/table/UserReqRow.tsx
  src/components/organisms/footer/Footer.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/table/Table.scss
  src/components/organisms/table/Table.tsx
  src/pages/ChangePassword.tsx
  src/pages/CompanyRequests.scss
  src/pages/CompanyRequests.tsx
  src/pages/CompanyUsers.scss
  src/pages/Devices.scss
  src/pages/Devices.tsx
  src/pages/Login.scss
  src/pages/Login.tsx
  src/pages/MainLayout.tsx
  src/pages/SignUp.scss
  src/pages/SignUp.tsx
  src/pages/UserRequests.tsx
  src/services/company.ts
  src/services/user.ts
  src/store/useAuthStore.ts
Labels: ✨ Feat, ♻️ Refactor, :hammer: Fix

#53 [Refactor] 유저 관리 페이지 리팩토링
  src/App.tsx
  src/components/molecules/monitoring/OverviewCardItem.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/monitoring/CompanyDeviceOverview.tsx
  src/components/organisms/monitoring/DeviceCardList.tsx
  src/pages/CompanyUsers.tsx
  src/pages/Summary.scss
  src/pages/Summary.tsx
  src/pages/Users.scss
  src/pages/Users.tsx
  src/types/Device.ts
Labels: ✨ Feat, ♻️ Refactor

#54 [Feat] 배치 모니터링 차트 구현
  src/App.tsx
  src/pages/BatchDashboard.scss
  src/pages/BatchDashboard.tsx
  src/services/batchMonitoring.ts
Labels: 🎨 Design, ✨ Feat

#55 [File] 파일 조회 및 다운로드 모달 창 구현 및 API 연결 진행
  package-lock.json
  package.json
  src/components/molecules/table/FileRow.scss
  src/components/molecules/table/FileRow.tsx
  src/components/organisms/header/Header.tsx
  src/components/organisms/modal/CompanyRegister.scss
  src/components/organisms/modal/FileViewer.scss
  src/components/organisms/modal/FileViewer.tsx
  src/pages/SignUp.scss
  src/pages/SignUp.tsx
  src/services/file.ts
Labels: 🎨 Design, ✨ Feat

#56 [Feat] 데이터베이스 등록 정보 페이지 권한에 따른 등록, 조회, 수정, 삭제 API 연결
  src/components/molecules/table/DevicesRow.tsx
  src/components/organisms/modal/DatabaseDelete.tsx
  src/components/organisms/modal/DatabaseForm.tsx
  src/components/organisms/table/Table.tsx
  src/pages/Devices.tsx
  src/services/device.ts
Labels: ✨ Feat

#60 [Feat] 파일 모달 연결
  src/components/molecules/table/FileRow.scss
  src/components/organisms/modal/FileViewer.scss
  src/pages/Summary.scss
  src/pages/Summary.tsx
Labels: ✨ Feat
